# Generated by Django 4.2.20 on 2025-06-12 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=45)),
                ('scheduled', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('max_partecipants', models.IntegerField(default=1)),
                ('imgs', models.ImageField(blank=True, help_text="Carica un'immagine del trattamento", null=True, upload_to='spa/')),
                ('type', models.CharField(choices=[('massage', 'Massaggio'), ('treatment', 'Trattamento'), ('ritual', 'Rituale')], default='massage', max_length=20)),
            ],
        ),
    ]
