# Generated by Django 5.1.7 on 2025-03-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('schedule', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('service_len', models.IntegerField(help_text='Durata del servizio in minuti')),
                ('price', models.IntegerField()),
                ('max_partecipants', models.IntegerField(default=1)),
                ('imgs', models.CharField(blank=True, help_text='URLs delle immagini', max_length=255)),
            ],
        ),
    ]
